=== igormorais123/pesquisa-eleitoral-df/agentes/perfis agentes sinteticos judiciário - STF, STJ, TJDF, TRF1/meta/schema_perfil_magistrado_v1.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "perfis-magistrados.schema.v1",
  "title": "PerfilMagistradoV1",
  "type": "object",
  "required": [
    "id",
    "nome",
    "orgao",
    "cargo",
    "situacao",
    "fontes",
    "atualizado_em"
  ],
  "properties": {
    "id": {
      "type": "string",
      "description": "Identificador estavel (slug)"
    },
    "nome": {
      "type": "string",
      "description": "Nome pelo qual e mais conhecido publicamente"
    },
    "nome_completo": {
      "type": ["string", "null"],
      "default": null
    },
    "orgao": {
      "type": "string",
      "enum": ["STF", "STJ", "TJDFT", "TRF1"],
      "description": "Orgao de atuacao (dataset atual)"
    },
    "cargo": {
      "type": "string",
      "description": "Ex: Ministro, Desembargador, Desembargador Federal"
    },
    "situacao": {
      "type": "string",
      "enum": ["titular", "substituto", "convocado", "nao_identificado"],
      "description": "Status no orgao (quando aplicavel)"
    },
    "dados_publicos": {
      "type": "object",
      "additionalProperties": true,
      "description": "Dados biograficos/publicos estruturados (somente informacoes publicas)"
    },
    "atuacao_profissional": {
      "type": "object",
      "additionalProperties": true,
      "description": "Trajetoria, cargos, areas, experiencias, producao"
    },
    "padroes_decisao": {
      "type": "object",
      "additionalProperties": true,
      "description": "Pistas empiricas: temas, teses, estilo de voto, deferencia, etc."
    },
    "hipoteses_para_simulacao": {
      "type": "object",
      "additionalProperties": true,
      "description": "Inferencias operacionais para simulacao (nao tratar como fato)"
    },
    "riscos_e_cuidados": {
      "type": "array",
      "items": {"type": "string"},
      "default": []
    },
    "fontes": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["url", "tipo"],
        "properties": {
          "url": {"type": "string"},
          "tipo": {
            "type": "string",
            "enum": [
              "site-oficial",
              "biografia",
              "curriculo",
              "entrevista",
              "artigo",
              "livro",
              "jurisprudencia",
              "noticia",
              "wikipedia",
              "outro"
            ]
          },
          "observacao": {"type": ["string", "null"], "default": null}
        },
        "additionalProperties": false
      }
    },
    "atualizado_em": {
      "type": "string",
      "description": "Data ISO (YYYY-MM-DD)"
    }
  },
  "additionalProperties": false
}

=== igormorais123/pesquisa-eleitoral-df/agentes/perfis agentes sinteticos judiciário - STF, STJ, TJDF, TRF1/TRF1/trf1-maura-moraes-tayer.json
{
  "id": "trf1-maura-moraes-tayer",
  "nome": "Maura Moraes Tayer",
  "nome_completo": null,
  "orgao": "TRF1",
  "cargo": "Desembargador Federal",
  "situacao": "titular",
  "dados_publicos": {
    "gabinete_texto": "Ed. Sede I - 3\u00ba andar - Sala 14",
    "funcao_administrativa": null,
    "pagina_trf1": "https://www.trf1.jus.br/trf1/em-atividade/maura-moraes-tayer",
    "telefone": "(61) 3314-5225",
    "biografia_trf1_texto": "**Nomeada por Decreto Presidencial de 13/09/2021, com posse e exerc\u00edcio em 08/10/2021.**\n\nData e Local de Nascimento: 26/09/1957, Para\u00fana-GO\n\n#### Atividade Profissional\n\nNome da Institui\u00e7\u00e3o: Justi\u00e7a Federal / Se\u00e7\u00e3o Judici\u00e1ria de Goi\u00e1s, 1\u00aa Vara, Goi\u00e2nia-GO / Fun\u00e7\u00e3o: Ju\u00edza Federal (Titular) Data de Admiss\u00e3o: 12/08/1992\n\nNome da Institui\u00e7\u00e3o: Pontif\u00edcia Universidade Cat\u00f3lica de Goi\u00e1s / Escola de Direito e Rela\u00e7\u00f5es Internacionais / Fun\u00e7\u00e3o: Professora Data de Admiss\u00e3o: 1996\n\n#### Atividades Profissionais Anteriores\n\nBanco Bandeirantes S/A Tipo de Atividade Exercida: Escritur\u00e1ria Per\u00edodo: 1977 a 1979;\n\nBanco do Estado de Goi\u00e1s Tipo de Atividade: Escritur\u00e1ria Per\u00edodo: 1980 a 1981;\n\nBanco do Estado de Goi\u00e1s Tipo de Atividade: Escritur\u00e1ria Per\u00edodo: 1980 a 1981;\n\nExerc\u00edcio de Advocacia no per\u00edodo de 1981 a 1983;\n\nMinist\u00e9rio P\u00fablico do Estado de Goi\u00e1s Tipo de Atividade: Promotora de Justi\u00e7a Per\u00edodo: 1983 a 1986;\n\nProcuradoria do Estado de Goi\u00e1s Cargo: Procuradora do Estado Per\u00edodo: 1986 a 1989;\n\nMinist\u00e9rio P\u00fablico Federal Cargo: Procuradora da Rep\u00fablica Per\u00edodo: 1989 a 1992.\n\n#### Atividades na Justi\u00e7a Federal\n\nJu\u00edza do Tribunal Regional Eleitoral no per\u00edodo de 26/08/1998 a 31/07/2000;\n\nDiretora do Foro da Se\u00e7\u00e3o Judici\u00e1ria de Goi\u00e1s no per\u00edodo de 01/05/1996 a 30/04/1997;\n\nPresidente da Turma Recursal do Juizado Federal da Se\u00e7\u00e3o Judici\u00e1ria de Goi\u00e1s no per\u00edodo de 14/03/2002 a 25/08/2004;\n\nSubstitui\u00e7\u00e3o e aux\u00edlio no gabinete do Desembargador Federal Jo\u00e3o Batista Gomes Moreira no per\u00edodo de 26/05/2009 a 30/12/2009.\n\n#### Forma\u00e7\u00e3o Acad\u00eamica/Titula\u00e7\u00e3o\n\nCurso Superior de Direito pela Universidade Federal de Goi\u00e1s, Goi\u00e2nia-GO,1976 a 1981;\n\nCurso de Especializa\u00e7\u00e3o em Direito Civil pela Universidade Federal de Goi\u00e1s, em Goi\u00e2nia-GO, conclu\u00eddo em 1982;\n\nCurso de Especializa\u00e7\u00e3o em Direito Processual Civil pela Universidade Federal de Goi\u00e1s, em Goi\u00e2nia, conclu\u00eddo em 1988;\n\nCurso de Especializa\u00e7\u00e3o em Direito Constitucional pela Academia de Pol\u00edcia de Goi\u00e1s, conclu\u00eddo em 1989;\n\nCurso de Mestrado em Direito pela Universidade Federal de Goi\u00e1s, Programa de Direito Agr\u00e1rio, com defesa de disserta\u00e7\u00e3o: Efetiva\u00e7\u00e3o Judicial das Normas Constitucionais sobre Reforma agr\u00e1ria, sendo orientador o Professor Doutor Joel Pimentel de Ulhoa, no per\u00edodo de 2000 a 2003.\n\n#### Aprova\u00e7\u00e3o em Concurso P\u00fablico\n\nMinist\u00e9rio P\u00fablico do Estado de Goi\u00e1s, cargo de Promotor de Justi\u00e7a, 3\u00aa Coloca\u00e7\u00e3o, 1983;\n\nProcuradoria do Estado de Goi\u00e1s, cargo de Procurador do Estado, 1\u00aa coloca\u00e7\u00e3o, 1986;\n\nMinist\u00e9rio P\u00fablico Federal, cargo de Procurador da Rep\u00fablica, 5\u00aa coloca\u00e7\u00e3o, 1989;\n\nTribunal Regional Federal da 1\u00aa Regi\u00e3o, cargo de Juiz Federal, 2\u00aa coloca\u00e7\u00e3o, 1992.\n\n#### Medalhas e Homenagens\n\nMedalha do M\u00e9rito Eleitoral Desembargador Jorge de Morais Jardim, conferida pelo Tribunal Regional Eleitoral de Goi\u00e1s \u2013 2005;\n\nMedalha de Grande-Oficial da Ordem do M\u00e9rito Anhanguera, conferida pelo Estado de Goi\u00e1s \u2013 2006."
  },
  "atuacao_profissional": {},
  "padroes_decisao": {},
  "hipoteses_para_simulacao": {
    "instrucoes": [
      "Inferencias aqui sao aproximacoes para simulacao; nao tratar como fato.",
      "Sempre rotular o agente como simulacao e evitar qualquer uso para enganar terceiros."
    ],
    "tracos_operacionais": [],
    "confianca_global": null
  },
  "riscos_e_cuidados": [
    "Nao usar para impersonacao (nao assinar como a pessoa real).",
    "Nao incluir dados pessoais nao-publicos."
  ],
  "fontes": [
    {
      "url": "https://www.trf1.jus.br/trf1/desembargadores-federais/em-atividade",
      "tipo": "site-oficial",
      "observacao": "Lista (Em atividade)"
    },
    {
      "url": "https://www.trf1.jus.br/trf1/em-atividade/maura-moraes-tayer",
      "tipo": "site-oficial",
      "observacao": "Pagina individual"
    }
  ],
  "atualizado_em": "2026-01-30"
}

=== igormorais123/pesquisa-eleitoral-df/agentes/perfis agentes sinteticos judiciário - STF, STJ, TJDF, TRF1/TJDFT/tjdft-mario-zam-belmiro-rosa.json
{
  "id": "tjdft-mario-zam-belmiro-rosa",
  "nome": "Des. M\u00e1rio-Zam Belmiro Rosa",
  "nome_completo": null,
  "orgao": "TJDFT",
  "cargo": "Desembargador",
  "situacao": "titular",
  "dados_publicos": {
    "assessor": "Claudia Regina Dias da Rocha",
    "telefones_gabinete": "(61)3103-6514, (61)3103-6512",
    "biografia_tjdft_url": "https://www.tjdft.jus.br/institucional/gestao-do-conhecimento/gestao-da-memoria/biografias/des-mario-zam-belmiro-rosa.pdf",
    "biografia_tjdft_texto": "89 \n \n \nBIOGRAFIA \nDESEMBARGADOR \nM\u00c1RIO-ZAM BELMIRO \n \nDADOS PESSOAIS \nNOME: Mario-Zam Belmiro Rosa \nDATA DE NASCIMENTO: 4/7/1957 \nLOCAL DE NASCIMENTO: Douradoquara - MG \nNACIONALIDADE: brasileira \n \n \n \n \n \n \n \n \nESCOLARIDADE \n \nCurso Superior: Bacharel em Direito pela Associa\u00e7\u00e3o de Ensino Unificado do Distrito Federal (AEUDF), \n1983. \n \n \nCARGOS OCUPADOS \n \n\u00bb Servi\u00e7os prestados a NOVACAP, 1976-1980. \n\u00bb Nomeado Auxiliar Judici\u00e1rio do Tribunal de Justi\u00e7a do Distrito Federal e dos Territ\u00f3rios (TJDFT), 1980-\n1984. \n\u00bb Promotor de Justi\u00e7a do Minist\u00e9rio P\u00fablico do Distrito Federal e Territ\u00f3rios (MPDFT), 1984-1988. \n\u00bb Nomeado Juiz de Direito Substituto da Justi\u00e7a do Distrito Federal, em 22/8/1988. \n\u00bb Promovido por merecimento a Juiz de Direito do TJDFT, em 30/9/1992. \n\u00bb Promovido por merecimento a Desembargador do TJDFT, em 26/10/2004. \n\u00bb Eleito para compor o Tribunal Regional Eleitoral \u2013 TRE/DF, como Membro Suplente, bi\u00eanio 2018/2020. \n\u00bb Eleito para o cargo de Corregedor do TJDFT para o bi\u00eanio 2024-2026 em 20/2/2024, com posse em \n22/4/2024. \n \nOUTROS T\u00cdTULOS \n \n\u00bb Outorgado com a Medalha do M\u00e9rito Eleitoral do DF, 2004. \n\u00bb Outorgado com a Comenda da Ordem do M\u00e9rito Judici\u00e1rio do Distrito Federal e dos Territ\u00f3rios no Grau \nde Gr\u00e3-Cruz, 2004. \n\u00bb Promovido ao grau \u201cGr\u00e3o-Colar\u201d pelo Conselho Tutelar da Comenda da Ordem do M\u00e9rito Judici\u00e1rio do \nDistrito Federal e dos Territ\u00f3rios, em 2010 (PRT OMJDFT 2 de 16 de mar\u00e7o de 2010). \n\u00bb Agraciado com a Medalha M\u00e9rito da Procudaria-Geral do Distrito Federal \u2013 em 26/4/2023 \n \nPROGRAMA HIST\u00d3RIA ORAL \n \n\u00bbYouTube/Playlist/Hist\u00f3riaOral/Mario-ZamBelmiroRosa",
    "biografia_tjdft_resumo": "89 \n \n \nBIOGRAFIA \nDESEMBARGADOR \nM\u00c1RIO-ZAM BELMIRO \n \nDADOS PESSOAIS \nNOME: Mario-Zam Belmiro Rosa \nDATA DE NASCIMENTO: 4/7/1957 \nLOCAL DE NASCIMENTO: Douradoquara - MG \nNACIONALIDADE: brasileira \n \n \n \n \n \n \n \n \nESCOLARIDADE \n \nCurso Superior: Bacharel em Direito pela Associa\u00e7\u00e3o de Ensino Unificado do Distrito Federal (AEUDF), \n1983. \n \n \nCARGOS OCUPADOS \n \n\u00bb Servi\u00e7os prestados a NOVACAP, 1976-1980. \n\u00bb Nomeado Auxiliar Judici\u00e1rio do Tribunal de Justi\u00e7a do Distrito Federal e dos Territ\u00f3rios (TJDFT), 1980-\n1984. \n\u00bb Promotor de Justi\u00e7a do Minist\u00e9rio P\u00fablico do Distrito Federal e Territ\u00f3rios (MPDFT), 1984-1988. \n\u00bb Nomeado Juiz de Direito Substituto da Justi\u00e7a do Distrito Federal, em 22/8/1988. \n\u00bb Promovido por merecimento a Juiz de Direito do TJDFT, em 30/9/1992. \n\u00bb Promovido por merecimento a Desembargador do TJDFT, em 26/10/2004. \n\u00bb Eleito para compor o Tribunal Regional Eleitoral \u2013 TRE/..."
  },
  "atuacao_profissional": {},
  "padroes_decisao": {},
  "hipoteses_para_simulacao": {
    "instrucoes": [
      "Inferencias aqui sao aproximacoes para simulacao; nao tratar como fato.",
      "Sempre rotular o agente como simulacao e evitar qualquer uso para enganar terceiros."
    ],
    "tracos_operacionais": [],
    "confianca_global": null
  },
  "riscos_e_cuidados": [
    "Nao usar para impersonacao (nao assinar como a pessoa real).",
    "Nao incluir dados pessoais nao-publicos."
  ],
  "fontes": [
    {
      "url": "https://www.tjdft.jus.br/institucional/composicao/2a-instancia/desembargadores/ordem-alfabetica",
      "tipo": "site-oficial",
      "observacao": "Ordem alfabetica (2a instancia)"
    }
  ],
  "atualizado_em": "2026-01-30"
}

=== igormorais123/pesquisa-eleitoral-df/agentes/perfis agentes sinteticos judiciário - STF, STJ, TJDF, TRF1/TRF1/trf1-marcelo-albernaz.json
{
  "id": "trf1-marcelo-albernaz",
  "nome": "Marcelo Albernaz",
  "nome_completo": null,
  "orgao": "TRF1",
  "cargo": "Desembargador Federal",
  "situacao": "titular",
  "dados_publicos": {
    "gabinete_texto": "Ed. Sede II - 9\u00ba andar - Sala 9S",
    "funcao_administrativa": null,
    "pagina_trf1": "https://www.trf1.jus.br/trf1/em-atividade/marcelo-albernaz",
    "telefone": "(61) 3314-5225",
    "biografia_trf1_texto": "**Marcelo Velasco Nascimento Albernaz**, nascido em Goi\u00e2nia/GO, no dia 21/12/1973. \u00c9 magistrado federal desde fevereiro de 1997, quando tomou posse no cargo de Juiz Federal Substituto, com primeira lota\u00e7\u00e3o na 3\u00aa Vara da Se\u00e7\u00e3o Judici\u00e1ria de Goi\u00e1s (c\u00edvel). Em 1999, foi promovido ao cargo de Juiz Federal da 1\u00aa Vara da Se\u00e7\u00e3o Judici\u00e1ria do Tocantins (compet\u00eancia geral), onde exerceu, em diversas oportunidades, as fun\u00e7\u00f5es de Vice-Diretor do Foro, Diretor do Foro e Presidente da Turma Recursal. Foi membro titular e substituto do Tribunal Regional Eleitoral do Estado do Tocantins por v\u00e1rios per\u00edodos, tendo exercido a fun\u00e7\u00e3o de Ouvidor Regional Eleitoral e de Corregedor Regional Eleitoral. Em 2012, foi removido para a Se\u00e7\u00e3o Judici\u00e1ria do Distrito Federal (SJDF), sendo sua \u00faltima lota\u00e7\u00e3o a 21\u00aa Vara, especializada em mat\u00e9ria de sa\u00fade, educa\u00e7\u00e3o e conselhos profissionais. Exerceu a fun\u00e7\u00e3o de Diretor do Foro da SJDF no bi\u00eanio de 2020-2022. Foi convocado para substitui\u00e7\u00e3o e aux\u00edlio de v\u00e1rios Desembargadores Federais do TRF1 de 2004 a 2023, tendo atuado, como juiz convocado, nas quatro se\u00e7\u00f5es especializadas e na Corregedoria Regional do Tribunal TRF1. Integrou listas consecutivas de promo\u00e7\u00e3o por merecimento em 2021, 2022 e 2023, sendo nomeado para exercer o cargo de Desembargador Federal do TRF1 em abril de 2023. Tomou posse como Desembargador Federal do TRF1 no dia 9/5/2023, integrando a Primeira Se\u00e7\u00e3o e a Primeira Turma. Antes de ingressar na magistratura federal, foi Fiscal de Posturas da Prefeitura de Goi\u00e2nia/GO (1992-1994), Delegado de Pol\u00edcia do Estado do Goi\u00e1s \u2013 1\u00ba lugar no concurso (1994), Promotor de Justi\u00e7a e Promotor Eleitoral do Estado de Goi\u00e1s \u2013 1\u00ba lugar do concurso (1994-1995) e Juiz Substituto e Juiz Eleitoral do Estado de Goi\u00e1s \u2013 1\u00ba lugar do concurso (1995-1997). Bacharel em Direito pela Universidade Cat\u00f3lica de Goi\u00e1s (atual PUC/GO) desde 1993, especializou-se em Direito Sanit\u00e1rio pela ESMPU/FIOCRUZ (2013) e concluiu mestrado em Ci\u00eancias Jur\u00eddicas pela Universidade Aut\u00f3noma de Lisboa (2018, com reconhecimento pela UCB em 2019). Concluiu cr\u00e9ditos de doutorado na Universidade Aut\u00f3noma de Lisboa, aguardando a elabora\u00e7\u00e3o de tese para conclus\u00e3o do curso. Durante a carreira profissional, frequentou v\u00e1rios cursos oficiais de curta e m\u00e9dia dura\u00e7\u00e3o ministrados por Escolas de Magistratura. Tem experi\u00eancia docente, principalmente nas \u00e1reas de Direito Civil, Processual Civil, Processual Penal, Eleitoral, Gest\u00e3o Judici\u00e1ria e Processo Eletr\u00f4nico. Foi agraciado com o t\u00edtulo de Cidad\u00e3o Tocantinense por meio da Lei Estadual n. 3.726/2020. Recebeu a Medalha Tiradentes (2005) e o Diploma de Colaborador Benem\u00e9rito (2010) da Pol\u00edcia Militar do Estado do Tocantins."
  },
  "atuacao_profissional": {},
  "padroes_decisao": {},
  "hipoteses_para_simulacao": {
    "instrucoes": [
      "Inferencias aqui sao aproximacoes para simulacao; nao tratar como fato.",
      "Sempre rotular o agente como simulacao e evitar qualquer uso para enganar terceiros."
    ],
    "tracos_operacionais": [],
    "confianca_global": null
  },
  "riscos_e_cuidados": [
    "Nao usar para impersonacao (nao assinar como a pessoa real).",
    "Nao incluir dados pessoais nao-publicos."
  ],
  "fontes": [
    {
      "url": "https://www.trf1.jus.br/trf1/desembargadores-federais/em-atividade",
      "tipo": "site-oficial",
      "observacao": "Lista (Em atividade)"
    },
    {
      "url": "https://www.trf1.jus.br/trf1/em-atividade/marcelo-albernaz",
      "tipo": "site-oficial",
      "observacao": "Pagina individual"
    }
  ],
  "atualizado_em": "2026-01-30"
}

=== igormorais123/pesquisa-eleitoral-df/agentes/perfis agentes sinteticos judiciário - STF, STJ, TJDF, TRF1/TJDFT/tjdft-maria-ivatonia-barbosa-dos-santos.json
{
  "id": "tjdft-maria-ivatonia-barbosa-dos-santos",
  "nome": "Desa. Maria Ivat\u00f4nia Barbosa dos Santos",
  "nome_completo": null,
  "orgao": "TJDFT",
  "cargo": "Desembargador",
  "situacao": "titular",
  "dados_publicos": {
    "assessor": "Juliana Menezes Mendes",
    "telefones_gabinete": "(61)3103-7596",
    "biografia_tjdft_url": "https://www.tjdft.jus.br/institucional/gestao-do-conhecimento/gestao-da-memoria/biografias/130-maria-ivatonia-barbosa-dos-santos.pdf",
    "biografia_tjdft_texto": "130 \nBIOGRAFIA \nDESEMBARGADORA \nMARIA IVAT\u00d4NIA \n \nDADOS PESSOAIS \nNOME: Maria Ivat\u00f4nia Barbosa dos Santos \nDATA DE NASCIMENTO: 15/8/1962 \nLOCAL DE NASCIMENTO: Arraias - TO \nNACIONALIDADE: brasileira \n \n \n \n \n \n \n \n \n \n \n \n \nESCOLARIDADE \n \nEnsino fundamental: Escola Municipal da Canabrava, Munic\u00edpio de Arraias- TO. \nEnsino m\u00e9dio: Instituto Nossa Senhora de Lourdes (Col\u00e9gio das Irm\u00e3s Dominicanas). \nEnsino superior: Bacharel em Direito em 1999, pela Universidade Cat\u00f3lica de Goi\u00e1s \u2013 UCG. \nP\u00f3s-Gradua\u00e7\u00e3o: \n\u00bb Especializa\u00e7\u00e3o em Direito Constitucional Eleitoral pela Universidade de Bras\u00edlia \u2013 UnB; \n\u00bb Especializa\u00e7\u00e3o em Direito Penal pela Universidade Cat\u00f3lica de Bras\u00edlia \u2013 UCB; \n\u00bb Especializa\u00e7\u00f5es em Direito Constitucional, Direito Administrativo, Criminal\u00edstica, Direito Penal e \nProcessual Penal, todas pela Universidade Cat\u00f3lica de Goi\u00e1s \u2013 UCG; \n\u00bb Reciclagem em Estudos Jur\u00eddicos pela Escola Superior da Magistratura do Estado de Goi\u00e1s. \n \nOutros Cursos \n\u00bb 1996/2003 - Franc\u00eas: Alian\u00e7a Francesa de Bras\u00edlia e Universidade de Nancy \u2013 Fran\u00e7a (n\u00edvel superior \u2013 \nconclus\u00e3o do Nancy III em 2003); \n\u00bb 1996/1999 - Alem\u00e3o: Goethe Instituto; 1999/2001; 2003/2004 \u2013 Espanhol: Associa\u00e7\u00e3o dos Magistrados do \nDistrito Federal (AMAGIS-DF); Centro de Cultura Hisp\u00e2nica; \n\u00bb 2001/2004 - Alem\u00e3o: Conversa\u00e7\u00e3o; \n\u00bb 2004/2005 - Italiano: Escola de L\u00ednguas da UnB; \n\u00bb 2007/2009 - Ingl\u00eas: curso intensivo. Instituto Brasas. \n \nEMPREGOS E CARGOS OCUPADOS \n \n\u00bb Auxiliar de Finan\u00e7as na Prefeitura Municipal de Arraias-TO. \n\u00bb Advocacia c\u00edvel e criminal no Escrit\u00f3rio de Advocacia Wanderley de Medeiros, Goi\u00e2nia-GO. \n\u00bb Exerceu o cargo de Delegada de Pol\u00edcia Civil do Estado de Goi\u00e1s. \n\u00bb Posse como Ju\u00edza de Direito Substituta do TJDFT em 7/5/1993. \n\u00bb Promovida para o cargo de Ju\u00edza de Direito em 1\u00ba/2/1996. - Atuou como Ju\u00edza Eleitoral da 12a Zona Eleitoral \nTRE-DF em 2003 e 2004. \n\u00bb Removida pelo crit\u00e9rio de merecimento ao cargo de Juiz de Direito Substituto de Segundo Grau, com posse \nem 15/4/2015, conforme Portaria GPR 554 de 27/3/2015. \n\u00bb Designada pela Presid\u00eancia do TJDFT para atuar como Juiz de Direito Substituto de Segundo Grau na 5\u00aa \nTurma C\u00edvel. \n\u00bb Desembargadora Eleitoral Substituta do TRE-DF de 25/8/2016 a 6/3/2017. \n\u00bb Desembargadora Eleitoral Titular do TRE-DF de 7/3/2017 a 7/3/2019. \n\u00bb Ouvidora do TRE-DF de 21/5/2018 a 7/3/2019. \n\u00bb Diretora da Revista da Escola da Magistratura do Distrito Federal de 2002 a 2008. \n\u00bb Ju\u00edza Coordenadora da Central de Guarda de Objetos de Crime \u2013 CEGOC, de 2009 a 2019. \n\u00bb Promovida, pelo crit\u00e9rio de antiguidade, ao cargo de Desembargadora do TJDFT, com posse em 12/12/2019. \n \nMAGIST\u00c9RIO \n \n\u00bb Professora de Reda\u00e7\u00e3o e Argumenta\u00e7\u00e3o Jur\u00eddica; Direito Penal Militar e Direito Processual Penal Militar \u2013 \nAuditoria Militar \u2013 na Escola Superior da Magistratura do Distrito Federal \u2013 2002 a 2008. \n\u00bb Professora de Portugu\u00eas do Curso de Forma\u00e7\u00e3o de Delegados de Pol\u00edcia na Academia de Pol\u00edcia Civil do \nEstado de Goi\u00e1s. \n\u00bb Professora de Portugu\u00eas (Ensino Fundamental e M\u00e9dio) no Externato S\u00e3o Jos\u00e9 (mesmo col\u00e9gio das Irm\u00e3s \nDominicanas em que cursou o ensino m\u00e9dio), em Goi\u00e2nia-GO. \n \nPARTICIPA\u00c7\u00c3O EM EVENTOS \n \n\u00bb Designado para constituir a comiss\u00e3o encarregada da elabora\u00e7 \u00e3o do Regulamento do Concurso e do \njulgamento das provas para Juiz Substituto da Justi\u00e7a do Distrito Federal, em 1970; \n\u00bb Designado membro da Comiss\u00e3o Especial para Assessorar a Forma\u00e7\u00e3o do Patrim\u00f4nio Art\u00edstico do \nPal\u00e1cio do Buriti, por solicita\u00e7\u00e3o do Governador do Distrito Federal H\u00e9lio Prates de Silveira; \n \nHOMENAGENS E HONRARIAS \n \n\u00bb Outorgada com a comenda da Ordem do M\u00e9rito Judici\u00e1rio do DF e dos Territ\u00f3rios, no grau de Comendadora, \nem 20/3/2001. \n\u00bb Condecorada com a Medalha do M\u00e9rito Eleitoral do Distrito Federal na classe jurista em 30/12/2002. \n\u00bb Promovida ao grau ''Gr\u00e3 -cruz'' da Ordem do M\u00e9rito Judici\u00e1rio do Distrito Federal e dos Territ\u00f3rios em \n2/9/2010. \n\u00bb Agraciado com a Medalha M\u00e9rito da Procudaria-Geral do Distrito Federal \u2013 em 26/4/2023.",
    "biografia_tjdft_resumo": "130 \nBIOGRAFIA \nDESEMBARGADORA \nMARIA IVAT\u00d4NIA \n \nDADOS PESSOAIS \nNOME: Maria Ivat\u00f4nia Barbosa dos Santos \nDATA DE NASCIMENTO: 15/8/1962 \nLOCAL DE NASCIMENTO: Arraias - TO \nNACIONALIDADE: brasileira \n \n \n \n \n \n \n \n \n \n \n \n \nESCOLARIDADE \n \nEnsino fundamental: Escola Municipal da Canabrava, Munic\u00edpio de Arraias- TO. \nEnsino m\u00e9dio: Instituto Nossa Senhora de Lourdes (Col\u00e9gio das Irm\u00e3s Dominicanas). \nEnsino superior: Bacharel em Direito em 1999, pela Universidade Cat\u00f3lica de Goi\u00e1s \u2013 UCG. \nP\u00f3s-Gradua\u00e7\u00e3o: \n\u00bb Especializa\u00e7\u00e3o em Direito Constitucional Eleitoral pela Universidade de Bras\u00edlia \u2013 UnB; \n\u00bb Especializa\u00e7\u00e3o em Direito Penal pela Universidade Cat\u00f3lica de Bras\u00edlia \u2013 UCB; \n\u00bb Especializa\u00e7\u00f5es em Direito Constitucional, Direito Administrativo, Criminal\u00edstica, Direito Penal e \nProcessual Penal, todas pela Universidade Cat\u00f3lica de Goi\u00e1s \u2013 UCG; \n\u00bb Reciclagem em Estudos Jur\u00eddicos pela Escola Super..."
  },
  "atuacao_profissional": {},
  "padroes_decisao": {},
  "hipoteses_para_simulacao": {
    "instrucoes": [
      "Inferencias aqui sao aproximacoes para simulacao; nao tratar como fato.",
      "Sempre rotular o agente como simulacao e evitar qualquer uso para enganar terceiros."
    ],
    "tracos_operacionais": [],
    "confianca_global": null
  },
  "riscos_e_cuidados": [
    "Nao usar para impersonacao (nao assinar como a pessoa real).",
    "Nao incluir dados pessoais nao-publicos."
  ],
  "fontes": [
    {
      "url": "https://www.tjdft.jus.br/institucional/composicao/2a-instancia/desembargadores/ordem-alfabetica",
      "tipo": "site-oficial",
      "observacao": "Ordem alfabetica (2a instancia)"
    }
  ],
  "atualizado_em": "2026-01-30"
}

=== igormorais123/pesquisa-eleitoral-df/agentes/perfis agentes sinteticos judiciário - STF, STJ, TJDF, TRF1/TRF1/trf1-pedro-braga-filho.json
{
  "id": "trf1-pedro-braga-filho",
  "nome": "Pedro Braga Filho",
  "nome_completo": null,
  "orgao": "TRF1",
  "cargo": "Desembargador Federal",
  "situacao": "titular",
  "dados_publicos": {
    "gabinete_texto": "Ed. Sede II - 1\u00ba andar - Sala 1N",
    "funcao_administrativa": null,
    "pagina_trf1": "https://www.trf1.jus.br/trf1/em-atividade/pedro-braga-filho",
    "telefone": "(61) 3314-5225",
    "biografia_trf1_texto": "Pedro Braga Filho, natural de Salvador/BA, filho de Pedro Braga e Odete Rodrigues Braga, foi nomeado por Decreto Presidencial de 18/10/2022 (DOU 19/10/2022) e tomou posse no TRF-1\u00aa Regi\u00e3o em 07/11/2022.\n\n#### Instru\u00e7\u00e3o\n\nBacharel em Direito pela Universidade Federal da Bahia (18/08/1978).\n\nMestre em Direito, \u00c1rea de Concentra\u00e7\u00e3o em Direito Econ\u00f4mico, pela Universidade Federal da Bahia (21/09/1998).\n\nAtividades Profissionais\n\nJuiz Federal Substituto, em 10/08/1992, na titularidade plena das 1\u00aa e 2\u00aa Varas da Se\u00e7\u00e3o Judici\u00e1ria do Piau\u00ed (1992 a 1993).\n\nRespondeu pela Se\u00e7\u00e3o Judici\u00e1ria do Piau\u00ed e foi Diretor do Foro (1992 a 1993).\n\nJuiz do Tribunal Regional Eleitoral do Piau\u00ed (1992 a 1993).\n\nJuiz Federal Substituto na titularidade plena e Juiz Federal da 1\u00aa Vara da Se\u00e7\u00e3o Judici\u00e1ria da Bahia (1993 a 2010).\n\nJuiz Diretor do Foro da Se\u00e7\u00e3o Judici\u00e1ria da Bahia (1996 a 1997).\n\nJuiz do Tribunal Regional Eleitoral da Bahia (16/09/1999 a 16/09/2001).\n\nMembro da 1\u00aa Turma Recursal da Se\u00e7\u00e3o Judici\u00e1ria da Bahia (2007 a 2008).\n\nPresidente da 2\u00aa Turma Recursal da Se\u00e7\u00e3o Judici\u00e1ria da Bahia (2008 a 2010), tendo participado neste per\u00edodo de sess\u00f5es da Turma Regional de Uniformiza\u00e7\u00e3o da 1\u00aa Regi\u00e3o.\n\nMembro da 1\u00aa C\u00e2mara Regional Previdenci\u00e1ria da Bahia (23/02/2015 a 23/08/2015).\n\nJuiz Federal Convocado para aux\u00edlio ao Tribunal Regional Federal da 1\u00aa Regi\u00e3o, em decorr\u00eancia das f\u00e9rias do Desembargador Federal Tourinho Neto, no per\u00edodo de 22/06/2009 a 21/07/2009.\n\nParticipou do Mutir\u00e3o das Turmas Recursais da Bahia, realizado de 16/03/2016 a 16/12/2016.\n\nJuiz Federal da 19\u00aa Vara da Se\u00e7\u00e3o judici\u00e1ria da Bahia (2010 a 2022).\n\nProcurador do Trabalho, Minist\u00e9rio P\u00fablico do Trabalho, no per\u00edodo de 17/12/1991 a 09/08/1992.\n\nMonitor concursado da disciplina Introdu\u00e7\u00e3o ao Estudo do Direito, Faculdade de Direito da Universidade Federal da Bahia (2\u00ba semestre de 1975 ao 1\u00ba semestre de 1978).\n\nProfessor Substituto (contratado) da disciplina Introdu\u00e7\u00e3o ao Estudo do Direito, Faculdade de Direito da Universidade Federal da Bahia (07/08/1995 a 31/12/1995).\n\nProfessor da FACS-Faculdades Salvador S/C (01/08/1990 a 31/07/1995-licenciado de 01/03/1992 a 31/07/1995), SESB-Sociedade de Ensino Superior da Bahia (01/03/1998 a 31/05/2000) e FACS S/C (01/06/2000 a 15/03/2002 e 01/03/2003 a 01/02/2005), tendo lecionado as disciplinas Institui\u00e7\u00f5es de Direito P\u00fablico e Privado, Direito Civil e Introdu\u00e7\u00e3o ao Estudo do Direito.\n\n#### Publica\u00e7\u00f5es\n\nO Condom\u00ednio Especial como Sujeito de Direito, na Revista Jur\u00eddica dos Formandos em Direito da UFBA, Ano II, Vol. II, 1997.\n\nGlobaliza\u00e7\u00e3o e a Teoria Geral dos Contratos, no livro Globaliza\u00e7\u00e3o e Direito, Coordenadores Adroaldo Le\u00e3o e Rodolfo Pamplona Filho, Rio de Janeiro, Forense, 2002.\n\nResponsabilidade tribut\u00e1ria de administradores e redirecionamento da execu\u00e7\u00e3o fiscal, na Cole\u00e7\u00e3o Jornada de Estudos Esmaf, 13 - II Jornada de Direito Tribut\u00e1rio, Tribunal Regional Federal da 1\u00aa Regi\u00e3o, Escola da Magistratura Federal da 1\u00aa Regi\u00e3o, Bras\u00edlia, ESMAF, 2012."
  },
  "atuacao_profissional": {},
  "padroes_decisao": {},
  "hipoteses_para_simulacao": {
    "instrucoes": [
      "Inferencias aqui sao aproximacoes para simulacao; nao tratar como fato.",
      "Sempre rotular o agente como simulacao e evitar qualquer uso para enganar terceiros."
    ],
    "tracos_operacionais": [],
    "confianca_global": null
  },
  "riscos_e_cuidados": [
    "Nao usar para impersonacao (nao assinar como a pessoa real).",
    "Nao incluir dados pessoais nao-publicos."
  ],
  "fontes": [
    {
      "url": "https://www.trf1.jus.br/trf1/desembargadores-federais/em-atividade",
      "tipo": "site-oficial",
      "observacao": "Lista (Em atividade)"
    },
    {
      "url": "https://www.trf1.jus.br/trf1/em-atividade/pedro-braga-filho",
      "tipo": "site-oficial",
      "observacao": "Pagina individual"
    }
  ],
  "atualizado_em": "2026-01-30"
}
